version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "34566-34599:4566-4599"
      - "9000:9000"
    environment:
      - SERVICES=sqs,sns,lambda
      - DEBUG=${DEBUG- }
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=9000
      - LAMBDA_EXECUTOR=docker
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - START_WEB=1
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - proxynet

  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports: 
      - "6379:6379"
    networks:
      - proxynet
      
    
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
        - REDIS_HOSTS=local:redis:6379
    ports:
        - "8081:8081"
    networks:
      - proxynet
    
networks:
  proxynet:
    name: local
